# Arg 1: the new package version
post_install() {

  # Create user and group
  systemd-sysusers sensu.conf

  # Required at this stage to ensure user & group are available
  chown -R sensu:sensu /opt/sensu
}

# Arg 1: the old package version
post_remove() {
  echo "This package does not automatically remove the sensu user and group."
  echo "Please do so manually if they are no longer required."
}

# vim:set ts=2 sw=2 et:
